### ISSUE TITLE
Client: TODO Status Code: 500

### ISSUE THREAD

**Issue by SavaLLL** [Alex7Kom/storekeeper#2]
Я получаю ошибку "Client: TODO Status Code: 500" в терминале, примерно каждые 5 минут.
На своем сайте я использую файл api.php который содержит:
<?php
require './callchedan/lib/server.php';
require './callchedan/lib/client.php';

$client = new Callchedan\Client('http://server.c9.io:8080/'); // storekeeper url
$admin = 'МОЙ_СТИМИД'; // put your steamid here so the bot can accept your offers

$methods = array(

  // answer 'pong' on message 'ping'
  'steam.friendMsg' => function ($params) use ($client, $admin) {
    if ($params['arguments'][1] == 'ping') {
      $client->call('steam.sendMessage', array($params['arguments'][0], 'pong'));
    }
  }

);

$server = new Callchedan\Server($methods);
echo $server->handle();
?>
Но при отправке ping в стиме ответа pong нет.
При просмотре файла через браузер я получаю ошибку: {"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"Invalid Request"}} Как я понял это правильно потому что браузер передает пустой запрос.
Можешь подсказать в чем проблема? Файл аккаунта вроде бы сконфигурирован правильно.

**Comment by Alex7Kom** [comment]
Sorry for the late reply. Check that Storekeeper URL you specified in your example is valid. You should also check the URL of PHP part of your application in your Storekeeper config.

And please use English here.

**Comment by vejbuch** [comment]
Hi,
please help me?

/usr/lib/node_modules/steam-storekeeper/lib/index.js:248
            throw error;
                  ^
Error: Access Denied
    at SteamTradeOffers.<anonymous> (/usr/lib/node_modules/steam-storekeeper/node_modules/steam-tradeoffers/index.js:90:25)
    at Request.self.callback (/usr/lib/node_modules/steam-storekeeper/node_modules/steam-tradeoffers/node_modules/request/request.js:354:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/lib/node_modules/steam-storekeeper/node_modules/steam-tradeoffers/node_modules/request/request.js:1207:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/steam-storekeeper/node_modules/steam-tradeoffers/node_modules/request/request.js:1153:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
