### ISSUE TITLE
Error: No options - SteamTradeOffers.acceptOffer

### ISSUE THREAD

**Issue by MaiKaY** [Alex7Kom/storekeeper#3]
Hi Alex7Kom,
i retrieve the following error:

```php
array(1) {
  [0] =>
  array(1) {
    'error' =>
    array(2) {
      'stack' =>
      string(749) "Error: No options
    at SteamTradeOffers.acceptOffer (/usr/local/lib/node_modules/steam-storekeeper/node_modules/steam-tradeoffers/index.js:323:16)
    at Object.tradeOffers.acceptOffer (/usr/local/lib/node_modules/steam-storekeeper/lib/index.js:293:52)
    at callHandler (/usr/local/lib/node_modules/steam-storekeeper/node_modules/node-json-rpc/lib/rpcserver.js:171:35)
    at dataHandler (/usr/local/lib/node_modules/steam-storekeeper/node_modules/node-json-rpc/lib/rpcserver.js:226:9)
    at IncomingMessage"...
      'message' =>
      string(10) "No options"
    }
  }
}
```
I'm using your Callchedan-lib and my call looks like you mentioned

```php
$tradeOfferId = '13371338';
$this->client->call('tradeOffers.acceptOffer', array($tradeOfferId));
```

Can you help me to resolve this issue?

regards
MaiKaY

**Comment by MaiKaY** [comment]
FYI

```php
$tradeOfferId = '13371338';
$this->client->call(
    'tradeOffers.acceptOffer',
    array(
        array('tradeOfferId' => $tradeOfferId)
    )
);
```
